# Generated by Django 6.0.6 on 2026-06-09 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('prazo', models.DateField()),
                ('prioridade', models.CharField(choices=[('urgente', 'Urgente'), ('alta', 'Alta'), ('media', 'Média'), ('baixa', 'Baixa')], max_length=20)),
                ('status', models.CharField(choices=[('em_espera', 'Em Espera'), ('iniciado', 'Iniciado'), ('finalizado', 'Finalizado')], max_length=20)),
            ],
        ),
    ]
