# Generated by Django 6.0.6 on 2026-06-10 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GTP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='nome',
            field=models.CharField(default='sem nome', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='prioridade',
            field=models.CharField(choices=[('urgente', 'Urgente'), ('alta', 'Alta'), ('media', 'Média'), ('baixa', 'Baixa')], default='media', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('em_espera', 'Em Espera'), ('iniciado', 'Iniciado'), ('finalizado', 'Finalizado')], default='em_espera', max_length=20),
        ),
    ]
