# Generated by Django 6.0.6 on 2026-06-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GTP', '0002_task_nome_alter_task_descricao_alter_task_prioridade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='prioridade',
            field=models.CharField(choices=[('urgente', 'Urgente'), ('alta', 'Alta'), ('media', 'Média'), ('baixa', 'Baixa')], default='Escolha uma opção...', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('em_espera', 'Em Espera'), ('iniciado', 'Iniciado'), ('finalizado', 'Finalizado')], default='Escolha uma opção...', max_length=20),
        ),
    ]
