# Generated by Django 6.0.6 on 2026-06-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GTP', '0005_alter_task_prioridade_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='lixeira',
            field=models.BooleanField(default=False),
        ),
    ]
