# Generated by Django 6.0.6 on 2026-06-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GTP', '0006_task_lixeira'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='localizacao',
            field=models.CharField(choices=[('ativa', 'Ativa'), ('lixeira', 'Lixeira')], default='ativa', max_length=20),
        ),
    ]
