# Generated by Django 6.0.6 on 2026-06-26 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GTP', '0007_task_localizacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='lixeira',
        ),
    ]
