# Generated by Django 6.0.6 on 2026-06-26 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GTP', '0008_remove_task_lixeira'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('em espera', 'Em Espera'), ('iniciado', 'Iniciado'), ('finalizado', 'Finalizado')], default='em espera', max_length=20),
        ),
    ]
